---
title: "Programming Exercises"
author: "Jon Griffiths"
date: "April 29, 2019"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)
library(knitr)
library(dplyr)
library(ggplot2)
library(purrr)
library(repurrrsive)
```

## Compute the number of unique values in each column of `iris`

### Using a `for` loop

```{r}

q1_loop_output <- vector(mode = "double", length = ncol(iris))
for (i in unique(iris)){
print(length(unique(i)))
}

```

### Using a `map` function

```{r}

map_int(iris, ~ length(unique(.)))

```

## Calculate the square of each element in vector `x`

```{r}
x <- 1:30
x
```

### Using a `for` loop

```{r}
q2_sqx <- vector(mode = "double")
for (i in range(x)) {
  q2_sqx <- (x^2)
}
q2_sqx
```

### Using a `map` function

```{r}
square_function <- function(x){
  x^2
}
x %>%
map_dbl(square_function)

```

## Write a function to calculate length of sides in a right-triangle using the Pythagorean Theorem

```{r}
#defines the 3 sides of the triangle
pythagorean <- function(side1, side2, hypo) {

#stops the function if any of the sides are not imputed as numeric
  
if (side1 != as.numeric(side1)) {
  stop("Invalid Input Type")
}
if (side2 != as.numeric(side2)) {
  stop("Invalid Input Type")
}
if (hypo != as.numeric(hypo)) {
  stop("Invalid Input Type")
}
  #indicates what sides must be present and what is returned under those circumstances
  if (side1 == TRUE| side2 == TRUE| hypo == FALSE) {
    hypotenuse <- sqrt(side1^2 + side2^2)
    return(hypotenuse)
  } else if (side1 == TRUE | hypo == TRUE | side2 == FALSE) {
    sidetwo <- sqrt(hypo^2 - side1^2)
    return(sidetwo)
  } else if (side2 == TRUE| hypo == TRUE| side1 == FALSE) {
    sideone <- sqrt(hypo^2 - side2^2)
    return(sideone)
  } else{
    #This is what is returned if there is a different number of inputs than specified above
    return("Invalid Number of Inputs") 
  }
}
```

## Session info

```{r}
devtools::session_info()
```


